FROM fedora:40

# renovate: datasource=git-refs depName=ggerganov/whisper.cpp packageName=https://github.com/ggerganov/whisper.cpp gitRef=master versioning=loose type=digest
ARG WHISPER_CPP_COMMIT=5caa19240d55bfd6ee316d50fbad32c6e9c39528

# renovate: datasource=github-releases depName=ggerganov/whisper.cpp
ARG WHISPER_CPP_VERSION=v1.6.1


RUN git clone https://github.com/ggerganov/whisper.cpp.git && \
    cd whisper.cpp && \
    git reset --hard ${WHISPER_CPP_COMMIT} && \
    make -j $(nproc) && \
    mv main /usr/bin/whisper-main && \
    mv server /usr/bin/whisper-server && \
    cd / && \
    rm -rf whisper.cpp
