FROM fedora:40

# renovate: datasource=git-refs depName=ggerganov/whisper.cpp packageName=https://github.com/ggerganov/whisper.cpp gitRef=master versioning=loose type=digest
ARG WHISPER_CPP_COMMIT=cbe557f9b1ae463c73358d902a622b90420b89d1

# renovate: datasource=github-releases depName=ggerganov/whisper.cpp
ARG WHISPER_CPP_VERSION=v1.6.1


RUN git clone https://github.com/ggerganov/whisper.cpp.git && \
    cd whisper.cpp && \
    git reset --hard ${WHISPER_CPP_COMMIT} && \
    make -j $(nproc) && \
    mv main /usr/bin/whisper-main && \
    mv server /usr/bin/whisper-server && \
    cd / && \
    rm -rf whisper.cpp
